import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import api from "../utils/api";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>HULU 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results data={results} />
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const genre = ctx.query.genre;

  const data = await api({
    url: requests[genre]?.url || requests.fetchTrending.url,
  });

  return {
    props: {
      results: data.data.results,
    },
  };
}
